### PR TITLE
Experiment: How hard is an online pull request 

### PR DESCRIPTION
**Pull request by frank-e**
This is supposed to add u.nuclear_submarine as suggested in http://freeciv.wikia.com/wiki/Variant2#Graphics only for 2.6 (ignoring 3.0 + master here, because I only want to see how this works. If you don't like the nuclear submarine by VS it's no problem, just reject it.)

### CODE REVIEW

**Comment by cazfi** [comment]
First line of the commit message should be of format: "<branch>/<modpack>: <short description>"

**Comment by frank-e** [comment]
What exactly is the "first line of a commit message"? I don't see a "/:" in your last Missing.txt commit on 
https://github.com/cazfi/fcmodpacks/commit/c70a5e5cc9ec9298921650b5754c760b2506a3f3#diff-72c6e6be3c7593df62f8b0e0dfce75d2 (using a browser, no Git for Windows involved.)

I doubt that the GitHub online UI let's me fix a commit message, if it already let me do something that isn't allowed :-(

**Comment by cazfi** [comment]
Github ate parts of my previous comment as something that looks like formatting. Let's try again: "S2_6/delta2: short description".
My previous commit handled all branches at once so it was just: "delta2: short description"
Also, short description should be imperative, e.g., "S2_6/delta2: Add Nuclear Submarine"

**Comment by frank-e** [comment]
Okay, got it, tested in https://github.com/frank-e/fcmodpacks/commit/4ea1383d819c6be0abc86cf4c5a8fce37c1cac15 for S2_6/delta2/delta2/Missing.txt, because I anyway forgot to remove the not more missing Nuclear Submarine.. Should I start a new pull request here? I don't see a way to edit the older commit messages, apart from delete fork and try again.

**Comment by cazfi** [comment]
Oh, this is three separate patches now? It should be just one patch, since the changes are not independent.

**Comment by frank-e** [comment]
As far as the online GUI is concerned it's no patch a all, only three commits, the older two without S2_6/delta2 in the header belonging to the old pull request, the 3rd not yet belonging to a pull request.

If there is a way to get more than one modification into one commit with this online GUI I certainly have not yet found it.  (But I see the problem, if this is not possible the online GUI is only suited for very simple patches affecting few files,)

**Pull request closed without merging**
